### ISSUE TITLE
the executable file

### ISSUE THREAD

**Issue by akk99** [TakTraum/cmdr#14]
Hi 
Great project! Traktor is a nightmare to edit large numbers of controls. 
Can't wait to give it a try. There is no executable to run, in the downloaded zip cmdr-master folder. 
Could you please let me know where to find the executable? 

Thanks 
Tom

_______________________
Just found. Here it is in case someone gets lost too: https://www.native-instruments.com/forum/threads/release-cmdr-controller-manager-done-right-new-2020-link.409243/

**Comment by pestrela** [comment]
two things:
- I'm maitaining a greatly updated versin of CMDR on my github. This is the improvements
https://github.com/pestrela/cmdr/blob/master/README.md#2020-improvements

this is the zip file:
https://github.com/pestrela/cmdr/releases/latest/download/cmdr_tsi_editor_latest.zip
- b) The exe can dissapear if your anti virus quarantines it. But you can safely white list it.
virustotal check: https://www.virustotal.com/gui/file/ab1db0d627782cfd55867addbac61d55be9debed9c3483ee527733eecf7b6610/detection

**Comment by akk99** [comment]
Many thanks for clarifying and apologies for a late reply.

Indeed, my antivirus does quarantine files too much.
