### ISSUE TITLE
*.exe file is gone in the repo

### ISSUE THREAD

**Issue by ThijsWaalders** [TakTraum/cmdr#16]
I can't start cmdr, Windows deleted the *.exe file. So I tried downloading it again, but the exe file is also missing in this repo.

**Comment by pestrela** [comment]
This project was moved permanently to a new location, and is getting updates moving forward
https://github.com/cmdr-editor/cmdr#2020-improvements

any developer is welcome to join this effort

**Comment by ThijsWaalders** [comment]
Thanks
