### ISSUE TITLE
Archive does not include executable

### ISSUE THREAD

**Issue by TVsVeryOwn** [TakTraum/cmdr#5]
I don't know how to compile, dude.

**Comment by manyfew** [comment]
Same here, where can we download the executable? Thanks

**Comment by ymmer** [comment]
you should download the relase zip, not the source. in there you find the executable.

https://github.com/TakTraum/cmdr/releases/download/v0.9.6/cmdr.v0.9.6.zip

**Comment by manyfew** [comment]
Got it, thanks! I'm not familiar with Github and hadn't noticed the "releases" tab. For anyone else reading this, the latest release can be found here: [https://github.com/TakTraum/cmdr/releases](https://github.com/TakTraum/cmdr/releases)
