### ISSUE TITLE
Can't find cmdr.exe file

### ISSUE THREAD

**Issue by jamsawamsa** [TakTraum/cmdr#7]

**Comment by jamsawamsa** [comment]
well, looks like i solved my own problem. You cant clone the repo, you've got to download cmdr0.9.6 in the releases tab to find the cmdr.exe file

**Comment by whiteschool** [comment]
I cant find the file in the download. Can you tell my how I have to do it pleasE? thanks

**Comment by b1aderunn3r** [comment]
Um, I have the same issue.  Can you help?
